import { readFile, writeFile, mkdir, copyFile } from "node:fs/promises";
import { supportConfig } from "../extension/support-config.js";
import { supportChannels } from "../extension/lib/support.js";

const escape = (text) => text.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
const { coffeeUrl } = supportChannels(supportConfig);
const supportLink = coffeeUrl ? `<p><a class="coffee-button" href="${escape(coffeeUrl)}" target="_blank" rel="noopener noreferrer">💵 Buy me a token</a></p>` : "";
const privacyKeys = ["privacyDate", "privacyData", "privacyLocal", "privacyStorage", "privacySharing", "privacySponsors", "privacyExport", "privacyLimitedUse", "privacyContact"];
const locales = {};
for (const locale of ["en", "zh_CN"]) locales[locale] = JSON.parse(await readFile(`extension/_locales/${locale}/messages.json`, "utf8"));
await mkdir("docs/site/assets", { recursive: true });
const sections = Object.entries(locales).map(([locale, messages]) => {
  const language = locale === "zh_CN" ? "zh-CN" : "en";
  return `<section id="${language}" lang="${language}"><h2>${escape(messages.privacyHeading.message)}</h2>${privacyKeys.map((key) => `<p>${escape(messages[key].message)}</p>`).join("\n")}</section>`;
}).join("\n");
const style = "body{max-width:850px;margin:48px auto;padding:0 24px;font:16px/1.7 -apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;color:#17243b;background:#f6f8fc}h1{line-height:1.2;font-size:32px}a{color:#2459d3}.coffee-button{display:inline-flex;align-items:center;gap:8px;background:#ffdd00;color:#000;border:1px solid #000;border-radius:8px;padding:9px 16px;text-decoration:none;font-weight:600}.coffee-button:hover{background:#ffe54c}section{background:#fff;padding:24px;border:1px solid #dce3ed;border-radius:12px;margin:24px 0}section:target{outline:2px solid #2459d3}img{max-width:100%;height:auto}nav{display:flex;gap:20px;flex-wrap:wrap}.note{color:#52627a;font-size:14px}@media(prefers-color-scheme:dark){body{background:#121925;color:#edf2fc}section{background:#1b2534;border-color:#344258}a{color:#8ab0ff}.note{color:#a7b6cc}}";
const shell = (title, body) => `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title}</title><style>${style}</style></head><body>${body}</body></html>\n`;
await writeFile("docs/site/privacy.html", shell("Privacy — Chrome Tabs Exporter", `<h1>Chrome Tabs Exporter</h1><nav><a href="index.html">Home / 首页</a><a href="#en">English</a><a href="#zh-CN">简体中文</a></nav>${sections}<footer><a href="https://github.com/wurining/chrome-tabs-exporter/issues">Contact / 联系发布者</a> · <a href="https://developer.chrome.com/docs/webstore/program-policies/user-data-faq">Chrome Web Store User Data Policy</a></footer>`));
const markdown = "# Chrome Tabs Exporter — Privacy policy / 隐私政策\n\n" + Object.entries(locales).map(([locale, messages]) => `## ${locale === "en" ? "English" : "简体中文"}\n\n${privacyKeys.map((key) => messages[key].message).join("\n\n")}\n`).join("\n") + "\nContact / 联系：[GitHub Issues](https://github.com/wurining/chrome-tabs-exporter/issues)\n";
await writeFile("PRIVACY.md", markdown);
await writeFile("docs/site/index.html", shell("Chrome Tabs Exporter", `<h1>Chrome Tabs Exporter</h1><p>Export open tabs and native tab groups to Markdown or JSON, and restore tabs from compatible JSON. File processing stays on your device.</p><p lang="zh-CN">将标签页与原生分组导出为 Markdown 或 JSON，也可以从兼容 JSON 恢复标签页，文件仅在本机处理。</p><nav><a href="https://github.com/wurining/chrome-tabs-exporter">Source / 源码</a><a href="https://github.com/wurining/chrome-tabs-exporter/releases">Download / 下载</a><a href="privacy.html">Privacy / 隐私政策</a><a href="https://github.com/wurining/chrome-tabs-exporter/issues">Support / 反馈</a></nav><section><h2>Local exports / 本地导出</h2><p>Select one or more normal windows, groups and individual tabs. Choose English or Simplified Chinese in Settings. Incognito windows and the extension's own pages are excluded.</p><p lang="zh-CN">勾选一个或多个普通窗口、分组和单个标签页；在设置中选择简体中文或英文。隐身窗口和本扩展自身页面均被排除。</p><p>Import JSON to preview and reopen URLs and groups in new windows or append them to the current window. Restoration visits those sites normally. Every feature is free; no file data is uploaded to the developer. Open source under MIT.</p><p lang="zh-CN">导入 JSON，预览后在新窗口恢复网址和分组，也可以追加到当前窗口。恢复会正常访问对应网站。全部功能免费，文件不上传给开发者，使用 MIT 许可证开源。</p></section><section><h2>Install / 安装</h2><p>Extract the release ZIP, open chrome://extensions, enable Developer mode and load the extracted folder. Requires Chrome 99+.</p><p lang="zh-CN">解压发布包，打开 chrome://extensions，启用开发者模式并加载解压文件夹。要求 Chrome 99 或更新版本。</p><p class="note">The Chrome Web Store listing has not been published yet. / Chrome 商店页面尚未发布。</p></section>${supportLink}<footer>© 2026 Chai Wang · Independent project / 独立项目</footer>`));
await writeFile("docs/site/.nojekyll", "");
await copyFile("docs/store-assets/icon-128.png", "docs/site/assets/icon-128.png");
console.log("Generated bilingual privacy Markdown and static public documentation from extension locale resources.");
