import { readFile, writeFile } from "node:fs/promises";
const locales = {};
for (const locale of ["en", "zh_CN"]) locales[locale] = JSON.parse(await readFile(`extension/_locales/${locale}/messages.json`, "utf8"));
await writeFile("extension/lib/messages.js", "// Generated by scripts/locales.mjs from the Chrome locale files.\nexport const localeMessages = " + JSON.stringify(locales, null, 2) + ";\n");
console.log("Generated packaged UI translations from Chrome locale files.");
